apiVersion: v1
kind: Pod
metadata:
  namespace : oleg
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myfirst-container
    image: verchol/multic:latest
    command: ['/bin/app']
    args: ["--server=true"]
  - name: mysecond-container
    image: verchol/multic:latest
    command: ['/bin/app']
    args: ["--client=true"]
  initContainers:
  - name: init-mydb
    image: alpine:latest
    command: ['sh', '-c', 'sleep 2']