apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp2
  namespace: default
spec:
  containers:
    - name: server
      image: verchol/multic:latest
      command: ['/bin/myapp']
      args: ["--server=true"]
    - name: client
      image: verchol/multic:latest
      command: ['/bin/myapp']
      args: ["--server=false",  "--client=true"]
    